---
name: New issue
about: Create an issue
title: ''
assignees: ''

---

This package is no longer maintained and has been replaced by [`boto3`](https://github.com/boto/boto3). Issues and pull requests are not reviewed. 
If you are having an issue with the [`boto3`](https://github.com/boto/boto3) package or the [AWS CLI](https://github.com/aws/aws-cli), please open an issue on their respective repositories.
